version: '3.5'
# 网络配置
networks:
  backend:
    driver: ${NETWORKS_DRIVER}

# 服务容器配置
services:
  gitlab:                                # 自定义容器名称
    build:
      context: ./gitlab                  # 指定构建使用的 Dockerfile 文件
    environment:                         # 设置环境变量
      - TZ=${TZ}
    volumes:                             # 设置挂载目录
      - ${GITLAB_PATH_CONFIG}:/etc/gitlab  # 引用 .env 配置 挂载宿主机目录给gitlab镜像使用
      - ${GITLAB_PATH_LOG}:/var/log/gitlab  # 引用 .env 配置
      - ${GITLAB_PATH_DATA}:/var/opt/gitlab  # 引用 .env 配置
    ports:                               # 设置端口映射
      - "443:443"                      # 443是暴露给宿主机的端口
      - "8080:80"                      # 8080是暴露给宿主机的端口
      - "22:22"
    networks:
      - backend
    restart: always                      # 指定容器退出后的重启策略为始终重启
